name: Frontend CI

on:
  push:
    branches: [main, entrega-inicial]
  pull_request:
    branches: [main, entrega-inicial]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm run test --if-present
      - name: Build project
        run: npm run build
